config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'pages#index'
  get 'home', to: redirect('/')
  get 'faqs', to: 'pages#faqs'
  get 'pricelist', to: 'pages#pricelist'
  get 'products', to: 'pages#products'

  namespace :admin do
    resources :orders, only: %i[index]
  end

  resources :users, only: %i[new create]
  namespace :auth do
    resources :email_confirmations, only: %i[new create]
    namespace :email_confirmations do
      post :resend
    end
    resources :password_reset_requests, only: %i[new create]
    resources :password_resets, only: %i[new create]
    resource :session, only: %i[new create destroy]
  end

  resources :locations, only: %i[index]
  resources :orders, only: %i[new edit update destroy index]
  resources :photos, only: :destroy

  get 'log_in', to: redirect('/auth/session/new')
  get 'sign_up', to: redirect('/users/new')
  delete 'log_out', to: 'auth/sessions#destroy'
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  SIZE_OPTIONS = [
    '9cm x 13cm',
    '10cm x 15cm',
    '13cm x 18cm',
    '15cm x 20cm',
    '15cm x 21cm',
    '20cm x 30cm',
    '30cm x 40cm',
    '30cm x 45cm'
  ].freeze
  SURFACE_OPTIONS = %w[glossy matte].freeze
  PAYMENT_METHOD_OPTIONS = %w[advance pickup].freeze
  DELIVERY_METHOD_PICKUP = 'pickup'
  DELIVERY_METHOD_POST = 'post'
  DELIVERY_METHOD_OPTIONS = [DELIVERY_METHOD_PICKUP, DELIVERY_METHOD_POST].freeze
  STATUS_NEW = 'new'
  STATUS_PLACED = 'placed'
  STATUS_CLOSED = 'closed'
  STATUS = [STATUS_NEW, STATUS_PLACED, STATUS_CLOSED].freeze

  belongs_to :location, optional: true
  belongs_to :user, optional: true
  has_many :order_items, dependent: :destroy
  has_many :photos, through: :order_items

  validates :size, presence: true, inclusion: { in: SIZE_OPTIONS }
  validates :surface, presence: true, inclusion: { in: SURFACE_OPTIONS }
  validates :white_frame, inclusion: { in: [true, false] }
  validates :amount, numericality: { only_integer: true, greater_than_or_equal_to: 1 }
  validates :delivery_method, presence: true, inclusion: { in: DELIVERY_METHOD_OPTIONS }
  validates :payment_method, presence: true, inclusion: { in: PAYMENT_METHOD_OPTIONS }
  validates :location, presence: true, if: :pickup?
  validates :status, inclusion: { in: STATUS }

  def self.build!(photos)
    transaction do
      o = new
      o.save(validate: false)
      photos.each do |photo|
        p = Photo.create(attachment: photo)
        OrderItem.create(photo: p, order: o)
      end
      o
    end
  end

  def pickup?
    delivery_method == DELIVERY_METHOD_PICKUP
  end

  def delivery_method_selection
    if pickup?
      location.id
    else
      DELIVERY_METHOD_POST
    end
  end

  def new?
    status == STATUS_NEW
  end

  def placed?
    status == STATUS_PLACED
  end
end

app/controllers/admin/orders_controller.rb
# frozen_string_literal: true

module Admin
  class OrdersController < AdminController
    def index
      @orders = Order.all
    end
  end
end

app/controllers/orders_controller.rb
# frozen_string_literal: true

class OrdersController < ApplicationController
  def index
    unless logged_in?
      redirect_to root_path
      return
    end

    @orders = current_user.orders
  end

  def new
    if session[:order_id]
      redirect_to edit_order_path(session[:order_id])
      return
    end

    order = Order.new(status: Order::STATUS_NEW).tap { |o| o.save(validate: false) }
    session[:order_id] = order.id
    redirect_to edit_order_path(order)
  end

  def edit
    @order = Order.find_by(id: params[:id])

    if @order.nil?
      # this probably means that the order in the user session has been deleted,
      # thus we should delete it from the session too...
      session[:order_id] = nil
      redirect_to new_order_path
    else
      handle_edit_order_exists
    end
  end

  def update
    @order = Order.find(params[:id])
    @locations = Location.all

    if allowed_order?(@order)
      update_order

      # After saving, associate the order with the logged in user (if logged in)
      UserOrderAssociationService.new(current_user, @order.id, session).perform
    else
      flash.now[:error] = t('orders.errors.order_not_allowed')
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    order = Order.find(params[:id])
    order.destroy!
    redirect_to root_path
  end

  private

  def update_order
    service = OrderUpdateService.new(@order, params)
    if service.perform
      handle_update_success
    else
      flash.now[:error] = t('orders.errors.order_not_updated')
      render :edit, status: :unprocessable_entity
    end
  end

  def handle_update_success
    flash[:success] = t('orders.success.order_updated')
    if logged_in?
      redirect_to orders_path
    else
      redirect_to root_path
    end
  end

  def handle_edit_order_exists
    @locations = Location.all

    if allowed_order?(@order)
      handle_edit_order_allowed
    else
      flash[:error] = t('orders.errors.order_not_allowed')
      redirect_to root_path
    end
  end

  def handle_edit_order_allowed
    if @order.placed?
      flash[:error] = t('orders.errors.order_placed')
      redirect_to orders_path
    else
      render :edit
    end
  end
end

app/helpers/orders_helper.rb
# frozen_string_literal: true

module OrdersHelper
  def white_frame_options
    [['Yes', true], ['No', false]]
  end

  def delivery_method_select_options(order, locations)
    location_options = locations.map { |location| [location.name, location.id] }
    post_option = [['by post', Order::DELIVERY_METHOD_POST]]
    options_for_select(location_options + post_option, order.delivery_method_selection)
  end
end

app/views/orders/edit.html.erb
<%= render 'errors', model: @order %>

<% # TODO: I18n for the select options %>

<% @order.photos.each do |photo| %>
  <div>
    <%= image_tag photo.attachment.variant(:thumb) %>
    <%= button_to 'delete', photo_path(photo), method: :delete %>
  </div>
<% end %>

<%= form_with model: @order, multipart: true do |f| %>
  <p>
    <%= f.label :photos %>
    <div class="dropzone dropzone-default dz-clickable" data-controller="dropzone" data-dropzone-accepted-files="image/*" data-dropzone-max-files="1000">
      <%= f.file_field :photos, multiple: true, direct_upload: true, data: { 'dropzone-target': 'input' } %>
      <div class="dropzone-msg dz-message needsclick text-gray-600">
        <h3 class="dropzone-msg-title">Drag here to upload or click here to browse</h3>
      </div>
    </div>
  </p>

  <p>
    <%= f.label :size %>
    <%= f.select :size, Order::SIZE_OPTIONS %>
  </p>
  <p>
    <%= f.label :surface %>
    <%= f.select :surface, Order::SURFACE_OPTIONS %>
  </p>
  <p>
    <%= f.label :white_frame %>
    <%= f.select :white_frame, white_frame_options %>
  </p>
  <p>
    <%= f.label :amount %>
    <%= f.number_field :amount, min: 1, step: 1 %>
  </p>
  <p>
    <%= f.label :special_requests %>
    <%= f.text_area :special_requests %>
  </p>
  <p>
    <%= f.label :delivery_method %>
    <%= f.select :delivery_method, delivery_method_select_options(@order, @locations), include_blank: true %>
  </p>
  <p>
    <%= f.label :payment_method %>
    <%= f.select :payment_method, Order::PAYMENT_METHOD_OPTIONS %>
  </p>
  <%= f.submit t('orders.submit_save') %>
  <%= f.submit t('orders.submit_place'), data: { 'turbo-confirm': t('orders.submit_place_confirmation') } %>
<% end %>

<%= button_to t('orders.submit_destroy'), order_path(@order), method: :delete %>

app/views/orders/index.html.erb
<h1><%= t(@orders.model_name.i18n_key, count: @orders.count) %></h1>

<p>
  <%# TODO i18n %>
  Note: Orders will be deleted automatically after they are fulfilled.
</p>

<% if @orders.any? %>

  <table>
    <tbody>
      <% @orders.each do |order| %>
        <tr>
          <td>
            <%= link_to edit_order_path(order) do %>
              <%# TODO i18n %>
              Order from <%= l(order.updated_at) %>
            <% end %>
          </td>
          <td><%= order.status %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

<% else %>
  <p>
    <%# TODO i18n %>
    You don't have any orders.
  </p>
<% end %>

<%= link_to "Create order", new_order_path %>