config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'pages#index'
  get 'home', to: redirect('/')
  get 'faqs', to: 'pages#faqs'
  get 'pricelist', to: 'pages#pricelist'
  get 'products', to: 'pages#products'

  namespace :admin do
    resources :orders, only: %i[index]
  end

  resources :users, only: %i[new create]
  namespace :auth do
    resources :email_confirmations, only: %i[new create]
    namespace :email_confirmations do
      post :resend
    end
    resources :password_reset_requests, only: %i[new create]
    resources :password_resets, only: %i[new create]
    resource :session, only: %i[new create destroy]
  end

  resources :locations, only: %i[index]
  resources :orders, only: %i[new edit update destroy index]
  resources :photos, only: :destroy

  get 'log_in', to: redirect('/auth/session/new')
  get 'sign_up', to: redirect('/users/new')
  delete 'log_out', to: 'auth/sessions#destroy'
end

app/views/layouts/_flashes.html.erb
<% if flash.any? %>
  <% flash.each do |type, msg| %>
    <%# TODO: style alerts correctly %>
    <div class="alert alert-<%= type %>">
      <%= msg %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class='flex-shrink-0 text-sm'>
  <div class='text-center bg-primary py-8 mt-8'>
    <p>© <%= Time.current.year %> <%= link_to 'Kodak Express', root_path %></p>
    <p><%= t('footer.credits')  %>
      <%= link_to 'Sei Online', 'https://www.seionline.ch', target: '_blank' %>
    </p>
  </div>
</footer>

app/views/layouts/_head.html.erb
  <head>
    <title><%= t('title') %></title>
    <html lang=<%= I18n.locale %>>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <% # Fonts %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300&display=swap" rel="stylesheet">

    <% # Favicon %>
    <%= favicon_link_tag asset_path('favicon.ico') %>
    <link rel="apple-touch-icon" href=<%= asset_path('favicon-32x32.png') %>>
    <link rel="icon" type="image/png" sizes="32x32" href=<%= asset_path('favicon-32x32.png') %>>
    <link rel="icon" type="image/png" sizes="16x16" href=<%= asset_path('favicon-16x16.png') %>>
    <link rel="manifest" href=<%= asset_path('site.webmanifest') %>>
    <%= javascript_importmap_tags %>
  </head>

app/views/layouts/_locations.html.erb
<div class='md:flex justify-center'>
  <% @locations.each do |location| %>
    <div class="max-w-sm rounded shadow-lg m-4 flex-1">
      <%= image_tag 'location.jpg', alt: t('activerecord.attributes.location.email') %>
      <div class="px-6 py-4">
        <h2><%= location.name %></h2>
        <p class='font-bold'><%= t('activerecord.attributes.location.opening_hours') %>:</p>
        <p><%= t('activerecord.attributes.location.days') %>: <%= location.opening_hours %></p>
        <br>
        <p class='font-bold'><%= t('activerecord.attributes.location.email') %>: <%= link_to location.email, "mailto:#{location.email}" %></p>
        <p class='font-bold'><%= t('activerecord.attributes.location.phone') %>: <%= link_to location.phone, "tel:#{location.phone}" %></p>
        <br>
        <p class='font-bold'><%= t('activerecord.attributes.location.address') %>:</p>
        <p><%= location.street %></p>
        <p><%= location.postcode %> <%=location.city %></p>
        <br>
        <p class='font-bold'><%= t('location.description_title') %>:</p>
        <p><%=location.description[I18n.locale.to_s] %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
    <nav data-controller="toggle" class="bg-secondary-color border-gray-200 px-2 sm:px-4 py-2.5">
      <div class="container flex justify-between flex-wrap mx-auto">
        <div>
          <%= link_to (image_tag 'kodak-logo-small.png', class: 'logo'), root_path %>
        </div>

        <button data-action="click->toggle#toggle" type="button" class="inline-flex justify-end p-2 ml-3 text-sm text-gray-500 md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200" aria-controls="navbar-default" aria-expanded="false">
          <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path></svg>
        </button>

        <div data-toggle-target="element" class="hidden w-full md:block md:w-auto" id="navbar-default">
          <ul class="flex flex-col p-4 mt-4 border border-gray-100 rounded-lg md:flex-row md:space-x-4 md:mt-0 md:text-sm md:font-medium md:border-0 bg-secondary-color">
            <li>
              <%= link_to t('navigation.online_order'), new_order_path, class: 'nav-item' %>
            </li>
            <li>
              <%= link_to t('navigation.services'), '#', class: 'nav-item' %>
            </li>
            <li>
              <%= link_to t('navigation.products'), products_path, class: 'nav-item' %>
            </li>
            <li>
              <%= link_to t('navigation.pricelist'), pricelist_path, class: 'nav-item' %>
            </li>
            <li>
              <%= link_to t('navigation.discounts'), '#', class: 'nav-item' %>
            </li>
            <li>
              <%= link_to t('navigation.locations'), "#{root_path}#locations", class: 'nav-item' %>
            </li>
            <li>
              <%= link_to t('navigation.faq'), faqs_path, class: 'nav-item' %>
            </li>
            <li>
              <%= link_to t('navigation.contact'), locations_path, class: 'nav-item' %>
            </li>
            <% if logged_in? %>
              <li>
                <%# TODO i18n %>
                Logged in as <%= current_user.name %>
              </li>
              <li>
                <%= link_to ActiveModel::Naming.plural(Order), orders_path, class: 'nav-item' %>
              </li>
              <li>
                <%= button_to t('auth.sessions.destroy.submit'), log_out_path, method: 'delete' %>
              </li>
            <% else %>
              <li>
                <a  class='nav-item' href=<%= new_auth_session_path %>>
                  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-5 h-5">
                    <path d="M10 8a3 3 0 100-6 3 3 0 000 6zM3.465 14.493a1.23 1.23 0 00.41 1.412A9.957 9.957 0 0010 18c2.31 0 4.438-.784 6.131-2.1.43-.333.604-.903.408-1.41a7.002 7.002 0 00-13.074.003z" />
                  </svg>
                </a>
              </li>
            <% end %>
            <li>
              <% if I18n.locale == :sk %>
                <%= locale_link t('navigation.english'), :en %>
              <% else %>
                <%= locale_link t('navigation.slovak'), :sk %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= render 'layouts/head' %>
  <body class='flex flex-col justify-between h-screen'>
    <div>
      <%= render 'layouts/navbar' %>
      <main class="container mx-auto mt-2 px-6 md:px-24">
        <%= render 'layouts/flashes' %>
        <%= yield %>
      </main>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/index.html.erb
<!DOCTYPE html>
<html>
  <%= render 'layouts/head' %>
  <body>
    <%= render 'layouts/navbar' %>
    <main>
      <%= render 'layouts/flashes' %>
      <%= yield %>
    </main>
  </body>
  <%= render 'layouts/footer' %>
</html>